# Generated by Django 5.1.2 on 2025-02-14 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodcheckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InjectionSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sites', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InsulinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('onset', models.CharField(help_text="Duration range (e.g., '15–30 min')", max_length=20)),
                ('peak_time', models.CharField(help_text="Duration range (e.g., '15–30 min')", max_length=20)),
                ('duration', models.CharField(help_text="Duration range (e.g., '15–30 min')", max_length=20)),
                ('method', models.CharField(choices=[('subcutaneous', 'Subcutaneous Injection'), ('intravenous', 'Intravenous Injection'), ('inhaled', 'Inhaled Insulin'), ('oral', 'Oral Insulin'), ('others', 'Others')], default='subcutaneous', help_text='Method of insulin administration', max_length=50)),
                ('info', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='bloodcheck',
            name='Bloodcheck_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.TextField(blank=True, null=True)),
                ('carbs', models.PositiveIntegerField(null=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsulinInjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insulin_type', models.CharField(max_length=30)),
                ('insulin_dose', models.DecimalField(decimal_places=2, max_digits=4)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('injection_site', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_insulin', models.BooleanField(default=False)),
                ('insulin_type', models.CharField(max_length=30)),
                ('is_pill', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
