# Generated by Django 5.1.2 on 2025-02-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_bloodchecktype_injectionsites_insulintype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodcheckType',
        ),
        migrations.RemoveField(
            model_name='bloodcheck',
            name='Bloodcheck_type',
        ),
        migrations.AddField(
            model_name='bloodcheck',
            name='event',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bloodcheck',
            name='bloodsugar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
